---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Checking for install at {{ actions_runner_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ actions_runner_install_dir }}'
  changed_when: false
  register: actions_runner_binary
- name: Downloading and installing actions runner
  when: not actions_runner_binary.stat.exists
  block:
    - name: Downloading {{ actions_runner_url }} to {{ actions_runner_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ actions_runner_url }}'
        dest: '{{ actions_runner_tmp_archive }}'
        checksum: '{{ actions_runner_checksum }}'
        mode: '644'
    - name: Mkdir {{ actions_runner_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ actions_runner_install_dir }}'
        mode: '755'
        state: directory
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ actions_runner_tmp_archive }} to {{ actions_runner_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ actions_runner_tmp_archive }}'
        dest: '{{ actions_runner_install_dir }}'
        creates: '{{ actions_runner_install_bin_dir }}'
  always:
    - name: Rm {{ actions_runner_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ actions_runner_tmp_archive }}'
        state: absent
